# Generated by Django 3.0.7 on 2020-09-01 06:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('New', '0022_auto_20200823_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 1, 12, 18, 6, 551501), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 1, 12, 18, 6, 554492), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 1, 12, 18, 6, 552498), verbose_name='Date'),
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='ok.jpg', upload_to='mob/')),
                ('color', models.CharField(choices=[('Red', 'R'), ('Blue', 'B'), ('Green', 'G')], max_length=5)),
                ('Price', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=789)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
