# Generated by Django 3.0.7 on 2020-07-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_account_dec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='dec',
        ),
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
