# Generated by Django 3.0.7 on 2020-07-31 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20200718_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rec', to=settings.AUTH_USER_MODEL)),
                ('sen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
