# Generated by Django 3.0.7 on 2020-07-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Range',
            field=models.CharField(choices=[('1-10', 'Noob'), ('10-20', 'Young'), ('20-30', 'OK'), ('30-40', 'uncle'), ('40-50', 'lol: uncle'), ('50-100', 'hello::grandpa')], default='30-40', max_length=6),
        ),
    ]
