# Generated by Django 3.0.7 on 2020-07-31 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_person_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 31, 23, 30, 32, 457463)),
        ),
    ]
