# Generated by Django 3.0.7 on 2020-07-31 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_person_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 31, 23, 31, 29, 95675)),
        ),
    ]
