# Generated by Django 3.0.7 on 2020-07-31 18:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0011_auto_20200801_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 1, 0, 21, 24, 511853)),
        ),
    ]
