# Generated by Django 3.0.7 on 2020-07-31 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200801_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 1, 0, 23, 27, 38654)),
        ),
    ]
