# Generated by Django 3.0.7 on 2020-07-31 18:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0013_auto_20200801_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Per',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=1000)),
                ('Range', models.CharField(choices=[('1-10', 'Noob'), ('10-20', 'Young'), ('20-30', 'OK'), ('30-40', 'uncle'), ('40-50', 'lol: uncle'), ('50-100', 'hello::grandpa')], default='30-40', max_length=6)),
                ('date', models.DateField(default=datetime.datetime(2020, 8, 1, 0, 29, 30, 328129))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
