# Generated by Django 3.0.7 on 2020-08-01 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200801_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='per',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 1, 17, 42, 42, 190415)),
        ),
    ]
