# Generated by Django 3.0.7 on 2020-08-01 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_delete_per'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mees',
        ),
    ]
